server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/careerdb
spring.datasource.username=root
spring.datasource.password=Priy@123*

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update